insert into Cars (Make, Model, Year) values ('Honda', 'Accord', 2007);
insert into Cars (Make, Model, Year) values ('Mitsubishi', 'Tredia', 1985);
insert into Cars (Make, Model, Year) values ('Mazda', 'MPV', 1997);
insert into Cars (Make, Model, Year) values ('BMW', 'X5', 2005);
insert into Cars (Make, Model, Year) values ('Ford', 'Crown Victoria', 1993);
insert into Cars (Make, Model, Year) values ('Mercedes-Benz', 'SLK55 AMG', 2009);
insert into Cars (Make, Model, Year) values ('Mercury', 'Mariner', 2010);
insert into Cars (Make, Model, Year) values ('Volkswagen', 'GTI', 2006);
insert into Cars (Make, Model, Year) values ('Ford', 'Five Hundred', 2005);
insert into Cars (Make, Model, Year) values ('Acura', 'Integra', 1993);
insert into Cars (Make, Model, Year) values ('GMC', 'Savana 1500', 2012);
insert into Cars (Make, Model, Year) values ('Lexus', 'IS-F', 2008);
insert into Cars (Make, Model, Year) values ('Toyota', '4Runner', 2008);
insert into Cars (Make, Model, Year) values ('Dodge', 'Durango', 2011);
insert into Cars (Make, Model, Year) values ('Lexus', 'HS', 2011);
insert into Cars (Make, Model, Year) values ('Lexus', 'GS', 1996);
insert into Cars (Make, Model, Year) values ('Mercedes-Benz', 'S-Class', 1985);
insert into Cars (Make, Model, Year) values ('Mercury', 'Capri', 1992);
insert into Cars (Make, Model, Year) values ('Infiniti', 'IPL G', 2012);
insert into Cars (Make, Model, Year) values ('Hyundai', 'Accent', 2007);
insert into Cars (Make, Model, Year) values ('Lexus', 'GS', 2000);
insert into Cars (Make, Model, Year) values ('Lamborghini', 'Diablo', 1991);
insert into Cars (Make, Model, Year) values ('Dodge', 'Ram 2500', 2001);
insert into Cars (Make, Model, Year) values ('Buick', 'Riviera', 1987);
insert into Cars (Make, Model, Year) values ('Mazda', 'B-Series', 2003);
insert into Cars (Make, Model, Year) values ('Chrysler', '300M', 2000);
insert into Cars (Make, Model, Year) values ('Volkswagen', 'riolet', 1992);
insert into Cars (Make, Model, Year) values ('Scion', 'tC', 2010);
insert into Cars (Make, Model, Year) values ('Chevrolet', 'Lumina', 1993);
insert into Cars (Make, Model, Year) values ('Toyota', 'Sequoia', 2010);
insert into Cars (Make, Model, Year) values ('Mercury', 'Grand Marquis', 2006);
insert into Cars (Make, Model, Year) values ('Volkswagen', 'Passat', 2009);
insert into Cars (Make, Model, Year) values ('Jeep', 'Wrangler', 2007);
insert into Cars (Make, Model, Year) values ('Mitsubishi', 'Diamante', 1998);
insert into Cars (Make, Model, Year) values ('Volvo', 'XC90', 2009);
insert into Cars (Make, Model, Year) values ('Buick', 'Rainier', 2007);
insert into Cars (Make, Model, Year) values ('Toyota', 'Celica', 2000);
insert into Cars (Make, Model, Year) values ('Mazda', 'Protege', 2000);
insert into Cars (Make, Model, Year) values ('Dodge', 'D250', 1993);
insert into Cars (Make, Model, Year) values ('Scion', 'tC', 2010);
insert into Cars (Make, Model, Year) values ('GMC', 'Sonoma Club Coupe', 1993);
insert into Cars (Make, Model, Year) values ('Infiniti', 'QX', 2006);
insert into Cars (Make, Model, Year) values ('Porsche', '911', 2001);
insert into Cars (Make, Model, Year) values ('Chevrolet', 'Colorado', 2005);
insert into Cars (Make, Model, Year) values ('Ford', 'Explorer', 2004);
insert into Cars (Make, Model, Year) values ('Ford', 'Taurus', 1993);
insert into Cars (Make, Model, Year) values ('Mercedes-Benz', 'S-Class', 2005);
insert into Cars (Make, Model, Year) values ('Toyota', 'Sienna', 1999);
insert into Cars (Make, Model, Year) values ('Pontiac', 'Aztek', 2001);
insert into Cars (Make, Model, Year) values ('Jeep', 'Grand Cherokee', 1993);

